services:
  - type: web
    name: nexora-auto-delivery
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.11
